---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    region: us-west-2
    keyname: yjkboto
    allowed_ip: 0.0.0.0/0 
    instance_type: t2.micro     
    image: ami-a9d09ed1
  tasks:  
    - name: Create key pair  
      tags: keypair  
      ec2_key:  
        region: "{{ region }}"  
        name: "{{ keyname }}"      
      register: akey  

    - name: Write the private key to file
      copy: content="{{ akey.key.private_key }}" dest="~/.ssh/{{ keyname }}.pem" mode=0600
      when: akey.changed

    - name: Create security group  
      tags: sg
      ec2_group:    
        region: "{{ region }}"
        name: yjk_sg    
        description: security group for host
        rules:
          - proto: tcp  
            from_port: 22  
            to_port: 22  
            cidr_ip: "{{ allowed_ip }}"  
          - proto: tcp  
            from_port: 80    
            to_port: 80    
            cidr_ip: 0.0.0.0/0    
          - proto: tcp  
            from_port: 443    
            to_port: 443    
            cidr_ip: 0.0.0.0/0
        rules_egress:  
          - proto: all  
            cidr_ip: 0.0.0.0/0    

    - name: Launch ec2 Instance  
      tags: ec2
      local_action:  
        module: ec2  
        region: "{{ region }}"  
        key_name: "{{ keyname }}"
        instance_type: "{{ instance_type }}"    
        image: "{{ image }}"  
        wait: yes    
        group: yjk_sg  
        instance_tags:  
          Name: wordpress-1  
          class: wordpress
      register: ec2    
    # - name: Associate new EIP for the instance  
    #   tags: eip      
    #   local_action:
    #     module: ec2_eip
    #     region: "{{ region }}"
    #     instance_id: "{{ item.id }}"
    #   with_items: ec2.instances   
    #   when: item.id is defined   
